# Generated by Django 3.0.2 on 2022-02-25 23:59

import api.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quarreler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(max_length=50)),
                ('updated_by', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', api.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=30)),
                ('guess1', models.CharField(max_length=30)),
                ('guess2', models.CharField(max_length=30)),
                ('guess3', models.CharField(max_length=30)),
                ('guess4', models.CharField(max_length=30)),
                ('guess5', models.CharField(max_length=30)),
                ('guess6', models.CharField(max_length=30)),
                ('solution_time', models.PositiveIntegerField()),
                ('correct_guess', models.PositiveIntegerField()),
                ('primary_elo', models.DecimalField(decimal_places=2, max_digits=8)),
                ('secondary_elo', models.DecimalField(decimal_places=2, max_digits=8)),
                ('elo_change', models.DecimalField(decimal_places=2, max_digits=8)),
                ('game_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('is_ranked', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(max_length=50)),
                ('updated_by', models.CharField(max_length=50)),
                ('primary_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primary_user', to='api.Quarreler')),
                ('secondary_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secondary_user', to='api.Quarreler')),
            ],
        ),
    ]
